// Ready-made dashboards over standard OpenTelemetry data and Leasyd's own series. Read-only:
// "Clone" makes an editable copy for the tenant. $service_name is the dashboard's service filter.
import type { Dashboard } from "./api";

const S = 'service_name=~"$service_name"';
const svc = [{ name: "service_name", label: "Service Name" }];
const text = (id: string, title: string, body: string, w = 3, h = 2) => ({ id, type: "text" as const, title, text: body, w, h });

export const BUILTIN: Dashboard[] = [
  {
    id: "builtin-services", builtin: true, version: 1, name: "Leasyd - Service overview",
    description: "Requests, errors and duration (RED) for every service, from its spans; and its logs.",
    variables: svc,
    panels: [
      text("about", "Overview", "Rate, errors and duration of each service, worked out from its spans (leasyd.spans, leasyd.span.duration), and its logs by severity.\n\nFilter with Service Name above.", 3, 2),
      { id: "rate", type: "timeseries", title: "Requests", description: "Server spans per second: requests each service received", w: 5, h: 2, unit: "/s",
        queries: [{ promql: `sum by (service_name) (rate(leasyd.spans{${S}, span_kind="SERVER"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "errors", type: "timeseries", title: "Errors", description: "Share of spans that failed (0 when none did)", w: 4, h: 2, unit: "%",
        queries: [{ promql: `100 * (sum by (service_name) (rate(leasyd.spans{${S}, status_code="ERROR"}[$__interval])) or 0 * sum by (service_name) (rate(leasyd.spans{${S}}[$__interval]))) / sum by (service_name) (rate(leasyd.spans{${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      text("aboutduration", "Duration", "How long requests take: the median (p50), and the slowest 5% and 1% (p95, p99).", 3, 2),
      { id: "p95", type: "timeseries", title: "Duration p95", description: "95% of server spans are faster than this", w: 5, h: 2, unit: "s",
        queries: [{ promql: `histogram_quantile(0.95, sum by (service_name) (rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "{{service_name}}" }] },
      { id: "pall", type: "timeseries", title: "Duration p50 / p95 / p99", description: "All services in the filter together", w: 4, h: 2, unit: "s",
        queries: [{ promql: `histogram_quantile(0.5, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p50" },
                  { promql: `histogram_quantile(0.95, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p95" },
                  { promql: `histogram_quantile(0.99, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p99" }] },
      { id: "slowest", type: "timeseries", title: "Slowest operations", description: "The 5 operations with the highest p95", w: 6, h: 2, unit: "s",
        queries: [{ promql: `topk(5, histogram_quantile(0.95, sum by (span_name) (rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval]))))`, legend: "{{span_name}}" }] },
      { id: "logs", type: "bars", title: "Logs by severity", description: "Log records per interval", w: 6, h: 2,
        queries: [{ promql: `sum by (severity_range) (increase(leasyd.logs{${S}}[$__interval]))`, legend: "{{severity_range}}" }] },
      { id: "spansnow", type: "stat", title: "Requests", description: "Server spans per second over the time range, all services in the filter", w: 3, h: 1, unit: "/s",
        queries: [{ promql: `sum(rate(leasyd.spans{${S}, span_kind="SERVER"}[$__range]))` }] },
      { id: "errorsnow", type: "stat", title: "Errors", description: "Share of spans that failed over the time range", w: 3, h: 1, unit: "%",
        queries: [{ promql: `100 * (sum(rate(leasyd.spans{${S}, status_code="ERROR"}[$__range])) or 0 * sum(rate(leasyd.spans{${S}}[$__range]))) / sum(rate(leasyd.spans{${S}}[$__range]))` }] },
      { id: "p95now", type: "stat", title: "Duration p95", description: "Server spans over the time range", w: 3, h: 1, unit: "s",
        queries: [{ promql: `histogram_quantile(0.95, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__range])))` }] },
      { id: "errorlogsnow", type: "stat", title: "Error logs", description: "ERROR and FATAL records per second over the time range", w: 3, h: 1, unit: "/s",
        queries: [{ promql: `sum(rate(leasyd.logs{${S}, severity_range="ERROR_FATAL"}[$__range]))` }] },
    ],
  },
  {
    id: "builtin-runtime", builtin: true, version: 1, name: "Leasyd - Process & HTTP metrics",
    description: "OpenTelemetry semantic-convention metrics: process CPU and memory, HTTP server requests and their duration, database connections.",
    variables: svc,
    panels: [
      text("about", "Process", "process.cpu.utilization and process.memory.usage, as OpenTelemetry SDKs and the Collector report them.", 3, 2),
      { id: "cpu", type: "timeseries", title: "CPU", description: "process.cpu.utilization (share of one CPU)", w: 5, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (service_name) (avg_over_time({"process.cpu.utilization", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "mem", type: "timeseries", title: "Memory", description: "process.memory.usage", w: 4, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.memory.usage", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      text("abouthttp", "HTTP server", "http.server.request.duration: how many requests each service handled, and how long the slowest 5% took (p95).", 3, 2),
      { id: "httprate", type: "timeseries", title: "HTTP requests", description: "Requests per second (the histogram's count)", w: 5, h: 2, unit: "/s",
        queries: [{ promql: `sum by (service_name) (rate({"http.server.request.duration_count", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "httpp95", type: "timeseries", title: "HTTP duration p95", description: "95% of requests are faster than this (from the histogram's buckets, in its own unit: OpenTelemetry's standard is seconds, some SDKs report ms)", w: 4, h: 2, unit: "ms",
        queries: [{ promql: `histogram_quantile(0.95, sum by (le, service_name) (rate({"http.server.request.duration_bucket", ${S}}[$__interval])))`, legend: "{{service_name}}" }] },
      { id: "httproute", type: "bars", title: "HTTP requests by route", description: "Requests per interval, by http.route", w: 6, h: 2,
        queries: [{ promql: `sum by (http_route) (increase({"http.server.request.duration_count", ${S}}[$__interval]))`, legend: "{{http_route}}" }] },
      { id: "db", type: "timeseries", title: "Database connections in use", description: "db.client.connections.usage", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"db.client.connections.usage", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-jvm", builtin: true, version: 1, name: "Leasyd - JVM",
    description: "Java services: heap and memory pools, garbage collection, threads, classes and CPU, from the OpenTelemetry Java agent's jvm.* metrics.",
    variables: svc,
    panels: [
      { id: "heapnow", type: "stat", title: "Heap used", description: "jvm.memory.used, heap pools, latest", w: 3, h: 1, unit: "bytes",
        queries: [{ promql: `sum(last_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[$__range]))` }] },
      { id: "cpunow", type: "stat", title: "CPU", description: "jvm.cpu.recent_utilization: share of the machine's CPU the JVM used, average over the range", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(avg_over_time({"jvm.cpu.recent_utilization", ${S}}[$__range]))` }] },
      { id: "gcnow", type: "stat", title: "Time in GC", description: "Share of time spent in garbage collection over the range (jvm.gc.duration), average of the services", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(sum by (service_name) (rate({"jvm.gc.duration_sum", ${S}}[$__range])))` }] },
      { id: "threadsnow", type: "stat", title: "Threads", description: "jvm.thread.count, latest", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(last_over_time({"jvm.thread.count", ${S}}[$__range]))` }] },
      { id: "heap", type: "timeseries", title: "Heap: used, committed, max", description: "jvm.memory.used / committed / limit for the heap. Used close to max means memory pressure.", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum(avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "used" },
                  { promql: `sum(avg_over_time({"jvm.memory.committed", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "committed" },
                  { promql: `sum(avg_over_time({"jvm.memory.limit", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "max" }] },
      { id: "cpu", type: "timeseries", title: "CPU", description: "jvm.cpu.recent_utilization by service", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (service_name) (avg_over_time({"jvm.cpu.recent_utilization", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "pools", type: "timeseries", title: "Heap by pool", description: "jvm.memory.used by pool (eden, survivor, old gen...): eden fills and empties with each young collection", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (jvm_memory_pool_name) (avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "{{jvm_memory_pool_name}}" }] },
      { id: "nonheap", type: "timeseries", title: "Non-heap by pool", description: "jvm.memory.used outside the heap: metaspace, code cache, compressed class space", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (jvm_memory_pool_name) (avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="non_heap"}[$__interval]))`, legend: "{{jvm_memory_pool_name}}" }] },
      { id: "gccount", type: "bars", title: "Garbage collections", description: "Collections per interval, by collector and action (jvm.gc.duration count)", w: 4, h: 2,
        queries: [{ promql: `sum by (jvm_gc_name) (increase({"jvm.gc.duration_count", ${S}}[$__interval]))`, legend: "{{jvm_gc_name}}" }] },
      { id: "gctime", type: "timeseries", title: "Time in GC", description: "Share of time spent collecting, by service", w: 4, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"jvm.gc.duration_sum", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "gcpause", type: "timeseries", title: "GC pause (average)", description: "Average time of one collection, by collector", w: 4, h: 2, unit: "s",
        queries: [{ promql: `sum by (jvm_gc_name) (rate({"jvm.gc.duration_sum", ${S}}[$__interval])) / sum by (jvm_gc_name) (rate({"jvm.gc.duration_count", ${S}}[$__interval]))`, legend: "{{jvm_gc_name}}" }] },
      { id: "threads", type: "timeseries", title: "Threads by state", description: "jvm.thread.count by jvm.thread.state (runnable, waiting, blocked...)", w: 6, h: 2,
        queries: [{ promql: `sum by (jvm_thread_state) (avg_over_time({"jvm.thread.count", ${S}}[$__interval]))`, legend: "{{jvm_thread_state}}" }] },
      { id: "classes", type: "timeseries", title: "Classes loaded", description: "jvm.class.count: classes currently loaded, by service", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"jvm.class.count", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-synthetics", builtin: true, version: 1, name: "Leasyd - Synthetic checks",
    description: "Uptime and response time of your synthetic checks, by check (under its current name); runs in maintenance windows left out.",
    variables: [],
    panels: [
      { id: "uptime", type: "timeseries", title: "Uptime", description: "Share of runs that passed", w: 6, h: 2, unit: "%",
        queries: [{ promql: '100 * sum by (check_id) (sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval])) / sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "duration", type: "timeseries", title: "Response time", description: "Time for all of a run's steps", w: 6, h: 2, unit: "ms",
        queries: [{ promql: 'avg by (check_id) (avg_over_time({"synthetics.check.duration"}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "fails", type: "bars", title: "Failed runs", description: "Runs that failed, per interval", w: 6, h: 2,
        queries: [{ promql: 'sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]) - sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "tls", type: "stat", title: "TLS certificate (days left)", description: "Days until the soonest certificate expires", w: 3, h: 2, decimals: 0,
        queries: [{ promql: 'min(last_over_time({"synthetics.check.tls_days_remaining"}[1h]))' }] },
      { id: "uptimenow", type: "stat", title: "Uptime", description: "Runs that passed over the time range, per check (as on each check's page)", w: 3, h: 2, unit: "%", decimals: 2,
        queries: [{ promql: '100 * sum by (check_id) (sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__range])) / sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__range]))', legend: "{{check_name}}" }] },
    ],
  },
];

export const isBuiltin = (id: string) => id.startsWith("builtin-");
