// Ready-made dashboards over standard OpenTelemetry data and Leasyd's own series. Read-only:
// "Clone" makes an editable copy for the tenant. $service_name is the dashboard's service filter.
import type { Dashboard } from "./api";

const S = 'service_name=~"$service_name"';
const H = '"host.name"=~"$host_name"';
// Lambda's per-function series (CloudWatch also sends each function by alias/version, and account totals)
const F = `${S}, FunctionName!="", Resource="", ExecutedVersion=""`;
const svc = [{ name: "service_name", label: "Service Name" }];
const text = (id: string, title: string, body: string, w = 3, h = 2) => ({ id, type: "text" as const, title, text: body, w, h });

export const BUILTIN: Dashboard[] = [
  {
    id: "builtin-services", builtin: true, version: 1, name: "Leasyd - Service overview",
    description: "Requests, errors and duration (RED) for every service, from its spans; and its logs.",
    variables: svc,
    panels: [
      text("about", "Overview", "Rate, errors and duration of each service, worked out from its spans (leasyd.spans, leasyd.span.duration), and its logs by severity.\n\nFilter with Service Name above.", 3, 2),
      { id: "rate", type: "timeseries", title: "Requests", description: "Server spans per second: requests each service received", w: 5, h: 2, unit: "/s",
        queries: [{ promql: `sum by (service_name) (rate(leasyd.spans{${S}, span_kind="SERVER"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "errors", type: "timeseries", title: "Errors", description: "Share of spans that failed (0 when none did)", w: 4, h: 2, unit: "%",
        queries: [{ promql: `100 * (sum by (service_name) (rate(leasyd.spans{${S}, status_code="ERROR"}[$__interval])) or 0 * sum by (service_name) (rate(leasyd.spans{${S}}[$__interval]))) / sum by (service_name) (rate(leasyd.spans{${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      text("aboutduration", "Duration", "How long requests take: the median (p50), and the slowest 5% and 1% (p95, p99).", 3, 2),
      { id: "p95", type: "timeseries", title: "Duration p95", description: "95% of server spans are faster than this", w: 5, h: 2, unit: "s",
        queries: [{ promql: `histogram_quantile(0.95, sum by (service_name) (rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "{{service_name}}" }] },
      { id: "pall", type: "timeseries", title: "Duration p50 / p95 / p99", description: "All services in the filter together", w: 4, h: 2, unit: "s",
        queries: [{ promql: `histogram_quantile(0.5, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p50" },
                  { promql: `histogram_quantile(0.95, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p95" },
                  { promql: `histogram_quantile(0.99, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval])))`, legend: "p99" }] },
      { id: "slowest", type: "timeseries", title: "Slowest operations", description: "The 5 operations with the highest p95", w: 6, h: 2, unit: "s",
        queries: [{ promql: `topk(5, histogram_quantile(0.95, sum by (span_name) (rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__interval]))))`, legend: "{{span_name}}" }] },
      { id: "logs", type: "bars", title: "Logs by severity", description: "Log records per interval", w: 6, h: 2,
        queries: [{ promql: `sum by (severity_range) (increase(leasyd.logs{${S}}[$__interval]))`, legend: "{{severity_range}}" }] },
      { id: "spansnow", type: "stat", title: "Requests", description: "Server spans per second over the time range, all services in the filter", w: 3, h: 1, unit: "/s",
        queries: [{ promql: `sum(rate(leasyd.spans{${S}, span_kind="SERVER"}[$__range]))` }] },
      { id: "errorsnow", type: "stat", title: "Errors", description: "Share of spans that failed over the time range", w: 3, h: 1, unit: "%",
        queries: [{ promql: `100 * (sum(rate(leasyd.spans{${S}, status_code="ERROR"}[$__range])) or 0 * sum(rate(leasyd.spans{${S}}[$__range]))) / sum(rate(leasyd.spans{${S}}[$__range]))` }] },
      { id: "p95now", type: "stat", title: "Duration p95", description: "Server spans over the time range", w: 3, h: 1, unit: "s",
        queries: [{ promql: `histogram_quantile(0.95, sum(rate(leasyd.span.duration{${S}, span_kind="SERVER"}[$__range])))` }] },
      { id: "errorlogsnow", type: "stat", title: "Error logs", description: "ERROR and FATAL records per second over the time range", w: 3, h: 1, unit: "/s",
        queries: [{ promql: `sum(rate(leasyd.logs{${S}, severity_range="ERROR_FATAL"}[$__range]))` }] },
    ],
  },
  {
    id: "builtin-runtime", builtin: true, version: 1, name: "Leasyd - Process & HTTP metrics",
    description: "OpenTelemetry semantic-convention metrics: process CPU and memory, HTTP server requests and their duration, database connections.",
    variables: svc,
    panels: [
      text("about", "Process", "process.cpu.utilization and process.memory.usage, as OpenTelemetry SDKs and the Collector report them.", 3, 2),
      { id: "cpu", type: "timeseries", title: "CPU", description: "process.cpu.utilization (share of one CPU)", w: 5, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (service_name) (avg_over_time({"process.cpu.utilization", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "mem", type: "timeseries", title: "Memory", description: "process.memory.usage", w: 4, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.memory.usage", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      text("abouthttp", "HTTP server", "http.server.request.duration: how many requests each service handled, and how long the slowest 5% took (p95).", 3, 2),
      { id: "httprate", type: "timeseries", title: "HTTP requests", description: "Requests per second (the histogram's count)", w: 5, h: 2, unit: "/s",
        queries: [{ promql: `sum by (service_name) (rate({"http.server.request.duration_count", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "httpp95", type: "timeseries", title: "HTTP duration p95", description: "95% of requests are faster than this (from the histogram's buckets, in its own unit: OpenTelemetry's standard is seconds, some SDKs report ms)", w: 4, h: 2, unit: "ms",
        queries: [{ promql: `histogram_quantile(0.95, sum by (le, service_name) (rate({"http.server.request.duration_bucket", ${S}}[$__interval])))`, legend: "{{service_name}}" }] },
      { id: "httproute", type: "bars", title: "HTTP requests by route", description: "Requests per interval, by http.route", w: 6, h: 2,
        queries: [{ promql: `sum by (http_route) (increase({"http.server.request.duration_count", ${S}}[$__interval]))`, legend: "{{http_route}}" }] },
      { id: "db", type: "timeseries", title: "Database connections in use", description: "db.client.connections.usage", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"db.client.connections.usage", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-jvm", builtin: true, version: 1, name: "Leasyd - JVM",
    description: "Java services: heap and memory pools, garbage collection, threads, classes and CPU, from the OpenTelemetry Java agent's jvm.* metrics.",
    variables: svc,
    panels: [
      { id: "heapnow", type: "stat", title: "Heap used", description: "jvm.memory.used, heap pools, latest", w: 3, h: 1, unit: "bytes",
        queries: [{ promql: `sum(last_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[2m]))` }] },
      { id: "cpunow", type: "stat", title: "CPU", description: "jvm.cpu.recent_utilization: share of the machine's CPU the JVM used, average over the range", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(avg_over_time({"jvm.cpu.recent_utilization", ${S}}[$__range]))` }] },
      { id: "gcnow", type: "stat", title: "Time in GC", description: "Share of time spent in garbage collection over the range (jvm.gc.duration), average of the services", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(sum by (service_name) (rate({"jvm.gc.duration_sum", ${S}}[$__range])))` }] },
      { id: "threadsnow", type: "stat", title: "Threads", description: "jvm.thread.count, latest", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(last_over_time({"jvm.thread.count", ${S}}[2m]))` }] },
      { id: "heap", type: "timeseries", title: "Heap: used, committed, max", description: "jvm.memory.used / committed / limit for the heap. Used close to max means memory pressure.", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum(avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "used" },
                  { promql: `sum(avg_over_time({"jvm.memory.committed", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "committed" },
                  { promql: `sum(avg_over_time({"jvm.memory.limit", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "max" }] },
      { id: "cpu", type: "timeseries", title: "CPU", description: "jvm.cpu.recent_utilization by service", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (service_name) (avg_over_time({"jvm.cpu.recent_utilization", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "pools", type: "timeseries", title: "Heap by pool", description: "jvm.memory.used by pool (eden, survivor, old gen...): eden fills and empties with each young collection", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (jvm_memory_pool_name) (avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="heap"}[$__interval]))`, legend: "{{jvm_memory_pool_name}}" }] },
      { id: "nonheap", type: "timeseries", title: "Non-heap by pool", description: "jvm.memory.used outside the heap: metaspace, code cache, compressed class space", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (jvm_memory_pool_name) (avg_over_time({"jvm.memory.used", ${S}, "jvm.memory.type"="non_heap"}[$__interval]))`, legend: "{{jvm_memory_pool_name}}" }] },
      { id: "gccount", type: "bars", title: "Garbage collections", description: "Collections per interval, by collector and action (jvm.gc.duration count)", w: 4, h: 2,
        queries: [{ promql: `sum by (jvm_gc_name) (increase({"jvm.gc.duration_count", ${S}}[$__interval]))`, legend: "{{jvm_gc_name}}" }] },
      { id: "gctime", type: "timeseries", title: "Time in GC", description: "Share of time spent collecting, by service", w: 4, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"jvm.gc.duration_sum", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "gcpause", type: "timeseries", title: "GC pause (average)", description: "Average time of one collection, by collector", w: 4, h: 2, unit: "s",
        queries: [{ promql: `sum by (jvm_gc_name) (rate({"jvm.gc.duration_sum", ${S}}[$__interval])) / sum by (jvm_gc_name) (rate({"jvm.gc.duration_count", ${S}}[$__interval]))`, legend: "{{jvm_gc_name}}" }] },
      { id: "threads", type: "timeseries", title: "Threads by state", description: "jvm.thread.count by jvm.thread.state (runnable, waiting, blocked...)", w: 6, h: 2,
        queries: [{ promql: `sum by (jvm_thread_state) (avg_over_time({"jvm.thread.count", ${S}}[$__interval]))`, legend: "{{jvm_thread_state}}" }] },
      { id: "classes", type: "timeseries", title: "Classes loaded", description: "jvm.class.count: classes currently loaded, by service", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"jvm.class.count", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-nodejs", builtin: true, version: 1, name: "Leasyd - Node.js",
    description: "Node.js services: event loop delay and utilization, V8 heap and garbage collection, from OpenTelemetry's Node.js runtime metrics (auto-instrumentation).",
    variables: svc,
    panels: [
      { id: "lagnow", type: "stat", title: "Event loop delay p99", description: "nodejs.eventloop.delay.p99, highest over the range: how late a callback can run", w: 3, h: 1, unit: "s",
        queries: [{ promql: `max(max_over_time({"nodejs.eventloop.delay.p99", ${S}}[$__range]))` }] },
      { id: "elunow", type: "stat", title: "Event loop busy", description: "nodejs.eventloop.utilization, average over the range", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(avg_over_time({"nodejs.eventloop.utilization", ${S}}[$__range]))` }] },
      { id: "heapnow", type: "stat", title: "Heap used", description: "v8js.memory.heap.used, all heap spaces, latest", w: 3, h: 1, unit: "bytes",
        queries: [{ promql: `sum(last_over_time({"v8js.memory.heap.used", ${S}}[2m]))` }] },
      { id: "gcnow", type: "stat", title: "Time in GC", description: "Share of time spent in garbage collection (v8js.gc.duration), average of the services", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(sum by (service_name) (rate({"v8js.gc.duration_sum", ${S}}[$__range])))` }] },
      { id: "lag", type: "timeseries", title: "Event loop delay", description: "nodejs.eventloop.delay: p50, p90 and p99. A blocked loop delays every request.", w: 6, h: 2, unit: "s",
        queries: [{ promql: `max(max_over_time({"nodejs.eventloop.delay.p50", ${S}}[$__interval]))`, legend: "p50" },
                  { promql: `max(max_over_time({"nodejs.eventloop.delay.p90", ${S}}[$__interval]))`, legend: "p90" },
                  { promql: `max(max_over_time({"nodejs.eventloop.delay.p99", ${S}}[$__interval]))`, legend: "p99" }] },
      { id: "elu", type: "timeseries", title: "Event loop utilization", description: "nodejs.eventloop.utilization: share of time the loop was busy, by service", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (service_name) (avg_over_time({"nodejs.eventloop.utilization", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "heap", type: "timeseries", title: "Heap: used and allocated", description: "v8js.memory.heap.used and v8js.memory.heap.space.size over all heap spaces. Used that keeps climbing after collections is a leak.", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum(avg_over_time({"v8js.memory.heap.used", ${S}}[$__interval]))`, legend: "used" },
                  { promql: `sum(avg_over_time({"v8js.memory.heap.space.size", ${S}}[$__interval]))`, legend: "allocated" }] },
      { id: "spaces", type: "timeseries", title: "Heap by space", description: "v8js.memory.heap.used by V8 heap space (new, old, code, large objects...)", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (v8js_heap_space_name) (avg_over_time({"v8js.memory.heap.used", ${S}}[$__interval]))`, legend: "{{v8js_heap_space_name}}" }] },
      { id: "gccount", type: "bars", title: "Garbage collections", description: "Collections per interval, by type (minor, major, incremental, weakcb)", w: 4, h: 2,
        queries: [{ promql: `sum by (v8js_gc_type) (increase({"v8js.gc.duration_count", ${S}}[$__interval]))`, legend: "{{v8js_gc_type}}" }] },
      { id: "gctime", type: "timeseries", title: "Time in GC", description: "Share of time spent collecting, by service", w: 4, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"v8js.gc.duration_sum", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "gcpause", type: "timeseries", title: "GC pause (average)", description: "Average time of one collection, by type", w: 4, h: 2, unit: "s",
        queries: [{ promql: `sum by (v8js_gc_type) (rate({"v8js.gc.duration_sum", ${S}}[$__interval])) / sum by (v8js_gc_type) (rate({"v8js.gc.duration_count", ${S}}[$__interval]))`, legend: "{{v8js_gc_type}}" }] },
      { id: "handles", type: "timeseries", title: "Active resources", description: "v8js.resource.active: timers, sockets and other handles keeping the process busy, by type. A steady climb is a leak.", w: 12, h: 2,
        queries: [{ promql: `sum by (v8js_resource_type) (avg_over_time({"v8js.resource.active", ${S}}[$__interval]))`, legend: "{{v8js_resource_type}}" }] },
    ],
  },
  {
    id: "builtin-python", builtin: true, version: 1, name: "Leasyd - Python",
    description: "Python services: CPU, memory, garbage collection, threads, file descriptors and context switches, from OpenTelemetry's system-metrics instrumentation (opentelemetry-instrumentation-system-metrics).",
    variables: svc,
    panels: [
      { id: "cpunow", type: "stat", title: "CPU", description: "process.cpu.time: share of one core used, average over the range", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `sum(rate({"process.cpu.time", ${S}, telemetry_sdk_language="python"}[$__range]))` }] },
      { id: "memnow", type: "stat", title: "Memory", description: "process.memory.usage (resident), latest, all services in the filter", w: 3, h: 1, unit: "bytes",
        queries: [{ promql: `sum(last_over_time({"process.memory.usage", ${S}, telemetry_sdk_language="python"}[2m]))` }] },
      { id: "gcnow", type: "stat", title: "GC collections", description: "cpython.gc.collections over the range, all generations", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(increase({"cpython.gc.collections", ${S}}[$__range]))` }] },
      { id: "threadsnow", type: "stat", title: "Threads", description: "process.thread.count, latest", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(last_over_time({"process.thread.count", ${S}, telemetry_sdk_language="python"}[2m]))` }] },
      { id: "cpu", type: "timeseries", title: "CPU", description: "process.cpu.time per second: share of one core, by service. Python runs one thread at a time per process, so near 100% means busy.", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"process.cpu.time", ${S}, telemetry_sdk_language="python"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "mem", type: "timeseries", title: "Memory (resident)", description: "process.memory.usage by service. Climbing without falling back is a leak.", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.memory.usage", ${S}, telemetry_sdk_language="python"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "gc", type: "bars", title: "GC collections by generation", description: "cpython.gc.collections per interval. Generation 2 (full) collections are the slow ones.", w: 6, h: 2,
        queries: [{ promql: `sum by (cpython_gc_generation) (increase({"cpython.gc.collections", ${S}}[$__interval]))`, legend: "generation {{cpython_gc_generation}}" }] },
      { id: "collected", type: "timeseries", title: "Objects collected", description: "cpython.gc.collected_objects per second, by generation", w: 6, h: 2, unit: "/s",
        queries: [{ promql: `sum by (cpython_gc_generation) (rate({"cpython.gc.collected_objects", ${S}}[$__interval]))`, legend: "generation {{cpython_gc_generation}}" }] },
      { id: "threads", type: "timeseries", title: "Threads", description: "process.thread.count by service", w: 4, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.thread.count", ${S}, telemetry_sdk_language="python"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "fds", type: "timeseries", title: "Open files and sockets", description: "process.open_file_descriptor.count by service. A steady climb is a leak.", w: 4, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.open_file_descriptor.count", ${S}, telemetry_sdk_language="python"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "ctx", type: "timeseries", title: "Context switches", description: "process.context_switches per second: voluntary (waiting on I/O) and involuntary (CPU contention)", w: 4, h: 2, unit: "/s",
        queries: [{ promql: `sum by (type) (rate({"process.context_switches", ${S}, telemetry_sdk_language="python"}[$__interval]))`, legend: "{{type}}" }] },
    ],
  },
  {
    id: "builtin-ruby", builtin: true, version: 1, name: "Leasyd - Ruby",
    description: "Ruby services: CPU, memory, threads, garbage collection and the object heap. Ruby's OpenTelemetry has no runtime metrics yet: add examples/ruby/leasyd_runtime_metrics.rb to your app.",
    variables: svc,
    panels: [
      { id: "cpunow", type: "stat", title: "CPU", description: "process.cpu.time: share of one core used, average over the range", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `sum(rate({"process.cpu.time", ${S}, telemetry_sdk_language="ruby"}[$__range]))` }] },
      { id: "memnow", type: "stat", title: "Memory", description: "process.memory.usage (resident), latest", w: 3, h: 1, unit: "bytes",
        queries: [{ promql: `sum(last_over_time({"process.memory.usage", ${S}, telemetry_sdk_language="ruby"}[2m]))` }] },
      { id: "gcnow", type: "stat", title: "Time in GC", description: "Share of time spent in garbage collection (ruby.gc.time), average of the services", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `avg(sum by (service_name) (rate({"ruby.gc.time", ${S}}[$__range])))` }] },
      { id: "threadsnow", type: "stat", title: "Threads", description: "process.thread.count, latest", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(last_over_time({"process.thread.count", ${S}, telemetry_sdk_language="ruby"}[2m]))` }] },
      { id: "cpu", type: "timeseries", title: "CPU", description: "process.cpu.time per second: share of one core, by service", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"process.cpu.time", ${S}, telemetry_sdk_language="ruby"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "mem", type: "timeseries", title: "Memory (resident)", description: "process.memory.usage by service", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.memory.usage", ${S}, telemetry_sdk_language="ruby"}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "gc", type: "bars", title: "Garbage collections", description: "ruby.gc.count and ruby.gc.major.count per interval. Major (full) collections are the slow ones.", w: 4, h: 2,
        queries: [{ promql: `sum(increase({"ruby.gc.count", ${S}}[$__interval])) - sum(increase({"ruby.gc.major.count", ${S}}[$__interval]))`, legend: "minor" },
                  { promql: `sum(increase({"ruby.gc.major.count", ${S}}[$__interval]))`, legend: "major" }] },
      { id: "gctime", type: "timeseries", title: "Time in GC", description: "ruby.gc.time per second: share of time collecting, by service", w: 4, h: 2, unit: "percentunit",
        queries: [{ promql: `sum by (service_name) (rate({"ruby.gc.time", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "alloc", type: "timeseries", title: "Allocations", description: "ruby.objects.allocated per second, by service. Fewer allocations, less GC.", w: 4, h: 2, unit: "/s",
        queries: [{ promql: `sum by (service_name) (rate({"ruby.objects.allocated", ${S}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "heap", type: "timeseries", title: "Object heap", description: "ruby.heap.live_slots and free_slots: objects alive, and room before the heap grows", w: 6, h: 2,
        queries: [{ promql: `sum(avg_over_time({"ruby.heap.live_slots", ${S}}[$__interval]))`, legend: "live" },
                  { promql: `sum(avg_over_time({"ruby.heap.free_slots", ${S}}[$__interval]))`, legend: "free" }] },
      { id: "threads", type: "timeseries", title: "Threads", description: "process.thread.count by service", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (avg_over_time({"process.thread.count", ${S}, telemetry_sdk_language="ruby"}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-lambda", builtin: true, version: 1, name: "Leasyd - AWS Lambda",
    description: "Lambda functions from CloudWatch: invocations, errors, duration, throttles and concurrency, from a CloudWatch metric stream (examples/aws/cloudwatch-metrics.yaml). Each function is a service.",
    variables: [{ name: "service_name", label: "Function" }],
    panels: [
      { id: "invnow", type: "stat", title: "Invocations", description: "All functions in the filter, over the range", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(sum_over_time({"aws.lambda.invocations_sum", ${F}}[$__range]))` }] },
      { id: "errnow", type: "stat", title: "Errors", description: "Share of invocations that failed, over the range", w: 3, h: 1, unit: "%",
        queries: [{ promql: `100 * sum(sum_over_time({"aws.lambda.errors_sum", ${F}}[$__range])) / sum(sum_over_time({"aws.lambda.invocations_sum", ${F}}[$__range]))` }] },
      { id: "durnow", type: "stat", title: "Duration (average)", description: "Average time an invocation ran, over the range", w: 3, h: 1, unit: "ms",
        queries: [{ promql: `sum(sum_over_time({"aws.lambda.duration_sum", ${F}}[$__range])) / sum(sum_over_time({"aws.lambda.duration_count", ${F}}[$__range]))` }] },
      { id: "thrnow", type: "stat", title: "Throttles", description: "Invocations refused for lack of concurrency, over the range", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `sum(sum_over_time({"aws.lambda.throttles_sum", ${F}}[$__range]))` }] },
      { id: "inv", type: "bars", title: "Invocations", description: "aws.lambda.invocations per interval, by function", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (sum_over_time({"aws.lambda.invocations_sum", ${F}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "err", type: "bars", title: "Errors", description: "aws.lambda.errors per interval, by function", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (sum_over_time({"aws.lambda.errors_sum", ${F}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "dur", type: "timeseries", title: "Duration (average)", description: "aws.lambda.duration: average time an invocation ran, by function", w: 6, h: 2, unit: "ms",
        queries: [{ promql: `sum by (service_name) (sum_over_time({"aws.lambda.duration_sum", ${F}}[$__interval])) / sum by (service_name) (sum_over_time({"aws.lambda.duration_count", ${F}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "slowest", type: "timeseries", title: "Slowest functions", description: "The 5 functions with the highest average duration", w: 6, h: 2, unit: "ms",
        queries: [{ promql: `topk(5, sum by (service_name) (sum_over_time({"aws.lambda.duration_sum", ${F}}[$__interval])) / sum by (service_name) (sum_over_time({"aws.lambda.duration_count", ${F}}[$__interval])))`, legend: "{{service_name}}" }] },
      { id: "conc", type: "timeseries", title: "Concurrent executions", description: "aws.lambda.concurrent_executions: instances running at once (average in the minute), by function", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (sum_over_time({"aws.lambda.concurrent_executions_sum", ${F}}[$__interval])) / sum by (service_name) (sum_over_time({"aws.lambda.concurrent_executions_count", ${F}}[$__interval]))`, legend: "{{service_name}}" }] },
      { id: "thr", type: "bars", title: "Throttles", description: "aws.lambda.throttles per interval, by function", w: 6, h: 2,
        queries: [{ promql: `sum by (service_name) (sum_over_time({"aws.lambda.throttles_sum", ${F}}[$__interval]))`, legend: "{{service_name}}" }] },
    ],
  },
  {
    id: "builtin-hosts", builtin: true, version: 1, name: "Leasyd - Hosts",
    description: "Servers: CPU, memory, load, disk, network and file systems, from the OpenTelemetry Collector's hostmetrics (examples/ec2/setup.sh sends them).",
    variables: [{ name: "host_name", label: "Host", field: "resource.host.name" }],
    panels: [
      { id: "cpunow", type: "stat", title: "CPU", description: "Share of CPU in use, average over the range and the hosts in the filter", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `1 - avg(avg_over_time({"system.cpu.utilization", ${H}, state="idle"}[$__range]))` }] },
      { id: "memnow", type: "stat", title: "Memory", description: "Share of memory in use, latest, highest of the hosts", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `max(last_over_time({"system.memory.utilization", ${H}, state="used"}[2m]))` }] },
      { id: "disknow", type: "stat", title: "Fullest disk", description: "The fullest file system, latest", w: 3, h: 1, unit: "percentunit",
        queries: [{ promql: `max(last_over_time({"system.filesystem.utilization", ${H}}[2m]))` }] },
      { id: "hostsnow", type: "stat", title: "Hosts", description: "Hosts sending metrics in the range", w: 3, h: 1, decimals: 0,
        queries: [{ promql: `count(count by (host_name) (count_over_time({"system.cpu.utilization", ${H}}[$__range])))` }] },
      { id: "cpu", type: "timeseries", title: "CPU", description: "system.cpu.utilization: share of all cores in use", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `1 - avg by (host_name) (avg_over_time({"system.cpu.utilization", ${H}, state="idle"}[$__interval]))`, legend: "{{host_name}}" }] },
      { id: "load", type: "timeseries", title: "Load average (1 min)", description: "system.cpu.load_average.1m: processes running or waiting for a CPU. Above the core count means they queue.", w: 6, h: 2,
        queries: [{ promql: `avg by (host_name) (avg_over_time({"system.cpu.load_average.1m", ${H}}[$__interval]))`, legend: "{{host_name}}" }] },
      { id: "mem", type: "timeseries", title: "Memory used", description: "system.memory.utilization, state used", w: 6, h: 2, unit: "percentunit",
        queries: [{ promql: `avg by (host_name) (avg_over_time({"system.memory.utilization", ${H}, state="used"}[$__interval]))`, legend: "{{host_name}}" }] },
      { id: "memstate", type: "timeseries", title: "Memory by state", description: "system.memory.usage: used, cached, buffered, free", w: 6, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (state) (avg_over_time({"system.memory.usage", ${H}}[$__interval]))`, legend: "{{state}}" }] },
      { id: "diskio", type: "timeseries", title: "Disk I/O", description: "system.disk.io: bytes read and written per second", w: 4, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (direction) (rate({"system.disk.io", ${H}}[$__interval]))`, legend: "{{direction}}" }] },
      { id: "netio", type: "timeseries", title: "Network", description: "system.network.io: bytes received and sent per second (not loopback)", w: 4, h: 2, unit: "bytes",
        queries: [{ promql: `sum by (direction) (rate({"system.network.io", ${H}, device!="lo"}[$__interval]))`, legend: "{{direction}}" }] },
      { id: "fs", type: "timeseries", title: "File systems", description: "system.filesystem.utilization: how full each mount is", w: 4, h: 2, unit: "percentunit",
        queries: [{ promql: `max by (host_name, mountpoint) (avg_over_time({"system.filesystem.utilization", ${H}}[$__interval]))`, legend: "{{host_name}} {{mountpoint}}" }] },
      { id: "procs", type: "timeseries", title: "Processes", description: "system.processes.count by status (running, sleeping, blocked...)", w: 6, h: 2,
        queries: [{ promql: `sum by (status) (avg_over_time({"system.processes.count", ${H}}[$__interval]))`, legend: "{{status}}" }] },
      { id: "conns", type: "timeseries", title: "TCP connections", description: "system.network.connections by state (ESTABLISHED, TIME_WAIT...)", w: 6, h: 2,
        queries: [{ promql: `sum by (state) (avg_over_time({"system.network.connections", ${H}, protocol="tcp"}[$__interval]))`, legend: "{{state}}" }] },
    ],
  },
  {
    id: "builtin-synthetics", builtin: true, version: 1, name: "Leasyd - Synthetic checks",
    description: "Uptime and response time of your synthetic checks, by check (under its current name); runs in maintenance windows left out.",
    variables: [],
    panels: [
      { id: "uptime", type: "timeseries", title: "Uptime", description: "Share of runs that passed", w: 6, h: 2, unit: "%",
        queries: [{ promql: '100 * sum by (check_id) (sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval])) / sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "duration", type: "timeseries", title: "Response time", description: "Time for all of a run's steps", w: 6, h: 2, unit: "ms",
        queries: [{ promql: 'avg by (check_id) (avg_over_time({"synthetics.check.duration"}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "fails", type: "bars", title: "Failed runs", description: "Runs that failed, per interval", w: 6, h: 2,
        queries: [{ promql: 'sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]) - sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__interval]))', legend: "{{check_name}}" }] },
      { id: "tls", type: "stat", title: "TLS certificate (days left)", description: "Days until the soonest certificate expires", w: 3, h: 2, decimals: 0,
        queries: [{ promql: 'min(last_over_time({"synthetics.check.tls_days_remaining"}[1h]))' }] },
      { id: "uptimenow", type: "stat", title: "Uptime", description: "Runs that passed over the time range, per check (as on each check's page)", w: 3, h: 2, unit: "%", decimals: 2,
        queries: [{ promql: '100 * sum by (check_id) (sum_over_time({"synthetics.check.success", "check.excluded"=""}[$__range])) / sum by (check_id) (count_over_time({"synthetics.check.success", "check.excluded"=""}[$__range]))', legend: "{{check_name}}" }] },
    ],
  },
];

export const isBuiltin = (id: string) => id.startsWith("builtin-");
